name: Build on click

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 2 * * 1"


jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fluffychat
        uses: actions/checkout@v4
        with:
          # repository: 'krille-chan/fluffychat'
          path: 'cleanchat'

      
  build_linux:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:

      - uses: actions/checkout@v4

      - run: cat .github/workflows/versions.env >> $GITHUB_ENV

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install curl clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libjsoncpp-dev cmake-data libsecret-1-dev libsecret-1-0 librhash0 libssl-dev libwebkit2gtk-4.1-dev webkit2gtk-4.1 -y
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - run: ./flutter/bin/flutter pub get

      - run: ./flutter/bin/flutter build linux --target-platform linux-x64

      - name: Create archive
        run: tar -czf fluffychat-linux-64.tar.gz -C build/linux/64/release/bundle/ .
      
      - name: Upload to artifact
        uses: actions/upload-artifact@v3
        with:
          name: cleanchat-linux-x64
          path: cleanchat/cleanchat-linux-x64.tar.gz
        # uses: actions/upload-release-asset@v1
        # with:
        #   upload_url: ${{ github.event.release.upload_url }}
        #   asset_path: cleanchat/cleanchat-linux-x64.tar.gz
        #   asset_name: cleanchat-linux-x64.tar.gz
        #   asset_content_type: application/gzip
        
          